-- MySQL Script generated by MySQL Workbench
-- Sun Nov 20 21:33:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NJIT_cs631103_carproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NJIT_cs631103_carproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NJIT_cs631103_carproject` DEFAULT CHARACTER SET utf8 ;
USE `NJIT_cs631103_carproject` ;

-- -----------------------------------------------------
-- Table `NJIT_cs631103_carproject`.`ClassCar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NJIT_cs631103_carproject`.`ClassCar` (
  `Name` VARCHAR(45) NOT NULL,
  `RateWeekly` DECIMAL(4) NOT NULL,
  `RateDaily` DECIMAL(4) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJIT_cs631103_carproject`.`CarModel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NJIT_cs631103_carproject`.`CarModel` (
  `carmodelID` INT NOT NULL,
  `Year` INT NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Make` VARCHAR(45) NULL DEFAULT NULL,
  `ClassCar_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`carmodelID`),
  INDEX `fk_CarModel_ClassCar1_idx` (`ClassCar_Name` ASC) VISIBLE,
  CONSTRAINT `fk_CarModel_ClassCar1`
    FOREIGN KEY (`ClassCar_Name`)
    REFERENCES `NJIT_cs631103_carproject`.`ClassCar` (`Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJIT_cs631103_carproject`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NJIT_cs631103_carproject`.`Car` (
  `VIM` VARCHAR(100) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `ClassCar_Name` VARCHAR(45) NOT NULL,
  `CarModel_carmodelID` INT NOT NULL,
  PRIMARY KEY (`VIM`),
  UNIQUE INDEX `VIM_UNIQUE` (`VIM` ASC) VISIBLE,
  INDEX `fk_Car_ClassCar1_idx` (`ClassCar_Name` ASC) VISIBLE,
  INDEX `fk_Car_CarModel1_idx` (`CarModel_carmodelID` ASC) VISIBLE,
  CONSTRAINT `fk_Car_ClassCar1`
    FOREIGN KEY (`ClassCar_Name`)
    REFERENCES `NJIT_cs631103_carproject`.`ClassCar` (`Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Car_CarModel1`
    FOREIGN KEY (`CarModel_carmodelID`)
    REFERENCES `NJIT_cs631103_carproject`.`CarModel` (`carmodelID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJIT_cs631103_carproject`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NJIT_cs631103_carproject`.`Location` (
  `LocationID` INT NOT NULL,
  `Phone` INT NOT NULL,
  `AStreet` VARCHAR(45) NOT NULL,
  `ACity` VARCHAR(45) NOT NULL,
  `AState` VARCHAR(2) NOT NULL,
  `AZip` VARCHAR(4) NOT NULL,
  `Car_VIM` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`LocationID`),
  INDEX `fk_Location_Car1_idx` (`Car_VIM` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Car1`
    FOREIGN KEY (`Car_VIM`)
    REFERENCES `NJIT_cs631103_carproject`.`Car` (`VIM`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJIT_cs631103_carproject`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NJIT_cs631103_carproject`.`Reservation` (
  `ReservationID` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `StartDate` DATE NULL DEFAULT NULL,
  `StartTime` TIME NULL DEFAULT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  `EndTime` TIME NULL DEFAULT NULL,
  `Type` VARCHAR(45) NULL DEFAULT NULL,
  `Pickup_LocationID` INT NOT NULL,
  `Return_LocationID` INT NOT NULL,
  `ClassCar_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ReservationID`),
  UNIQUE INDEX `ReservationID_UNIQUE` (`ReservationID` ASC) VISIBLE,
  INDEX `fk_Reservation_Location1_idx` (`Pickup_LocationID` ASC) VISIBLE,
  INDEX `fk_Reservation_Location2_idx` (`Return_LocationID` ASC) VISIBLE,
  INDEX `fk_Reservation_ClassCar1_idx` (`ClassCar_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Location1`
    FOREIGN KEY (`Pickup_LocationID`)
    REFERENCES `NJIT_cs631103_carproject`.`Location` (`LocationID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reservation_Location2`
    FOREIGN KEY (`Return_LocationID`)
    REFERENCES `NJIT_cs631103_carproject`.`Location` (`LocationID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reservation_ClassCar1`
    FOREIGN KEY (`ClassCar_Name`)
    REFERENCES `NJIT_cs631103_carproject`.`ClassCar` (`Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJIT_cs631103_carproject`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NJIT_cs631103_carproject`.`Customer` (
  `customerID` INT NOT NULL,
  `FName` VARCHAR(45) NOT NULL,
  `LName` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `LcNumber` VARCHAR(45) NULL DEFAULT NULL,
  `LcState` VARCHAR(2) NULL DEFAULT NULL,
  `CCType` VARCHAR(45) NULL DEFAULT NULL,
  `CCNumber` INT NULL DEFAULT NULL,
  `AStreet` VARCHAR(45) NULL DEFAULT NULL,
  `ACity` VARCHAR(45) NULL DEFAULT NULL,
  `AState` VARCHAR(2) NULL DEFAULT NULL,
  `Azip` VARCHAR(4) NULL DEFAULT NULL,
  `Reservation_ReservationID` INT NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `customerID_UNIQUE` (`customerID` ASC) VISIBLE,
  INDEX `fk_Customer_Reservation_idx` (`Reservation_ReservationID` ASC) VISIBLE,
  UNIQUE INDEX `LcNumber_UNIQUE` (`LcNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Reservation`
    FOREIGN KEY (`Reservation_ReservationID`)
    REFERENCES `NJIT_cs631103_carproject`.`Reservation` (`ReservationID`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJIT_cs631103_carproject`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NJIT_cs631103_carproject`.`Invoice` (
  `InvoiceID` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Taxes` DECIMAL NULL DEFAULT NULL,
  `Total` DECIMAL NULL DEFAULT NULL,
  PRIMARY KEY (`InvoiceID`),
  UNIQUE INDEX `InvoiceID_UNIQUE` (`InvoiceID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NJIT_cs631103_carproject`.`Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NJIT_cs631103_carproject`.`Agreement` (
  `ContractNumber` INT NOT NULL,
  `StartTime` TIME NULL DEFAULT NULL,
  `ReturnTime` TIME NULL DEFAULT NULL,
  `StartDate` DATE NULL DEFAULT NULL,
  `ReturnDate` DATE NULL DEFAULT NULL,
  `StartOdometer` INT NULL DEFAULT NULL,
  `EndOdometer` INT NULL DEFAULT NULL,
  `Reservation_ReservationID` INT NOT NULL,
  `Invoice_InvoiceID` INT NULL,
  `Car_VIM` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ContractNumber`),
  UNIQUE INDEX `ContractNumber_UNIQUE` (`ContractNumber` ASC) VISIBLE,
  INDEX `fk_Agreement_Reservation1_idx` (`Reservation_ReservationID` ASC) VISIBLE,
  INDEX `fk_Agreement_Invoice1_idx` (`Invoice_InvoiceID` ASC) VISIBLE,
  INDEX `fk_Agreement_Car1_idx` (`Car_VIM` ASC) VISIBLE,
  CONSTRAINT `fk_Agreement_Reservation1`
    FOREIGN KEY (`Reservation_ReservationID`)
    REFERENCES `NJIT_cs631103_carproject`.`Reservation` (`ReservationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Agreement_Invoice1`
    FOREIGN KEY (`Invoice_InvoiceID`)
    REFERENCES `NJIT_cs631103_carproject`.`Invoice` (`InvoiceID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Agreement_Car1`
    FOREIGN KEY (`Car_VIM`)
    REFERENCES `NJIT_cs631103_carproject`.`Car` (`VIM`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
